=== apnadmin/appynotebook/src/conf/xml-resources/jaxb/AppletPackageManifest/applet-package.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://xml.netbeans.org/schema/applet-package"
    xmlns:tns="http://xml.netbeans.org/schema/applet-package"
    elementFormDefault="qualified">
    <xsd:complexType name="applet">
        <xsd:sequence>
            <xsd:element name="id" type="xsd:string"/>
            <xsd:element name="name" type="xsd:string"/>
            <xsd:element name="description" type="xsd:string"/>
            <xsd:element name="iconPath" type="xsd:string"/>
            <xsd:element name="version" type="xsd:string"/>
            <xsd:element name="authorName" type="xsd:string"/>
            <xsd:element name="authorLink" type="xsd:string"/>
            <xsd:element name="categoryId" type="xsd:string"/>
            <xsd:element name="tags" type="xsd:string"/>
            <xsd:element name="createDate" type="xsd:dateTime"/>
            <xsd:element name="lastModifiedDate" type="xsd:dateTime"/>
            <xsd:element name="showInMenu" type="xsd:string"/>
            <xsd:element name="codePath" type="xsd:string"/>
            <xsd:element name="resources" minOccurs="0">
                <xsd:complexType>
                    <xsd:sequence maxOccurs="unbounded">
                        <xsd:element name="resource" type="tns:resource"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="dependencies" minOccurs="0">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="resource" type="tns:resource" maxOccurs="unbounded"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="resource">
        <xsd:sequence>
            <xsd:element name="fileName" type="xsd:string"/>
            <xsd:element name="label" type="xsd:string"/>
            <xsd:element name="fsName" type="xsd:string"/>
            <xsd:element name="type" type="xsd:string"/>
            <xsd:element name="mime" type="xsd:string"/>
            <xsd:element name="size" type="xsd:string"/>
            <xsd:element name="createDate" type="xsd:dateTime"/>
            <xsd:element name="lastModifiedDate" type="xsd:dateTime"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:element name="package">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="name" type="xsd:string"/>
                <xsd:element name="version" type="xsd:string"/>
                <xsd:element name="description" type="xsd:string"/>
                <xsd:element name="license" type="xsd:string"/>
                <xsd:element name="restrictToDomain" type="xsd:string" minOccurs="0"/>
                <xsd:element name="publicKey" type="xsd:string" minOccurs="0"/>
                <xsd:element name="uuid" type="xsd:string"/>
                <xsd:element name="applets">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="applet" type="tns:applet" maxOccurs="unbounded"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== apnadmin/appynotebook/src/java/com/feezixlabs/util/test-package-manifest.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : test-package-manifest.xml
    Created on : December 19, 2010, 7:18 PM
    Author     : bitlooter
    Description:
        Purpose of the document follows.
-->

<ns1:package  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns:ns1='http://xml.netbeans.org/schema/applet-package'
   xsi:schemaLocation='http://xml.netbeans.org/schema/applet-package file:/home/bitlooter/development/java/feezixlabs/src/java/com/feezixlabs/util/applet-package.xsd'>
    <ns1:name></ns1:name>
    <ns1:version></ns1:version>
    <ns1:description></ns1:description>
    <ns1:applets>
        <ns1:applet>
            <ns1:name></ns1:name>
            <ns1:description></ns1:description>
            <ns1:iconPath></ns1:iconPath>
            <ns1:version></ns1:version>
            <ns1:authorName></ns1:authorName>
            <ns1:authorLink></ns1:authorLink>
            <ns1:categoryId></ns1:categoryId>
            <ns1:tags></ns1:tags>
            <ns1:createDate></ns1:createDate>
            <ns1:lastModifiedDate></ns1:lastModifiedDate>
            <ns1:showInMenu></ns1:showInMenu>
            <ns1:codePath></ns1:codePath>
            <ns1:resources>
                <ns1:resource>
                    <ns1:fileName></ns1:fileName>
                    <ns1:label></ns1:label>
                    <ns1:fsName></ns1:fsName>
                    <ns1:type></ns1:type>
                    <ns1:mime></ns1:mime>
                    <ns1:size></ns1:size>
                    <ns1:createDate></ns1:createDate>
                    <ns1:lastModifiedDate></ns1:lastModifiedDate>
                </ns1:resource>
            </ns1:resources>
        </ns1:applet>
        <ns1:applet>
            <ns1:name></ns1:name>
            <ns1:description></ns1:description>
            <ns1:iconPath></ns1:iconPath>
            <ns1:version></ns1:version>
            <ns1:authorName></ns1:authorName>
            <ns1:authorLink></ns1:authorLink>
            <ns1:categoryId></ns1:categoryId>
            <ns1:tags></ns1:tags>
            <ns1:createDate></ns1:createDate>
            <ns1:lastModifiedDate></ns1:lastModifiedDate>
            <ns1:showInMenu></ns1:showInMenu>
            <ns1:codePath></ns1:codePath>
            <ns1:resources>
                <ns1:resource>
                    <ns1:fileName></ns1:fileName>
                    <ns1:label></ns1:label>
                    <ns1:fsName></ns1:fsName>
                    <ns1:type></ns1:type>
                    <ns1:mime></ns1:mime>
                    <ns1:size></ns1:size>
                    <ns1:createDate></ns1:createDate>
                    <ns1:lastModifiedDate></ns1:lastModifiedDate>
                </ns1:resource>
            </ns1:resources>
        </ns1:applet>
        <ns1:applet>
            <ns1:name></ns1:name>
            <ns1:description></ns1:description>
            <ns1:iconPath></ns1:iconPath>
            <ns1:version></ns1:version>
            <ns1:authorName></ns1:authorName>
            <ns1:authorLink></ns1:authorLink>
            <ns1:categoryId></ns1:categoryId>
            <ns1:tags></ns1:tags>
            <ns1:createDate></ns1:createDate>
            <ns1:lastModifiedDate></ns1:lastModifiedDate>
            <ns1:showInMenu></ns1:showInMenu>
            <ns1:codePath></ns1:codePath>
            <ns1:resources>
                <ns1:resource>
                    <ns1:fileName></ns1:fileName>
                    <ns1:label></ns1:label>
                    <ns1:fsName></ns1:fsName>
                    <ns1:type></ns1:type>
                    <ns1:mime></ns1:mime>
                    <ns1:size></ns1:size>
                    <ns1:createDate></ns1:createDate>
                    <ns1:lastModifiedDate></ns1:lastModifiedDate>
                </ns1:resource>
            </ns1:resources>
        </ns1:applet>
    </ns1:applets>

</ns1:package>
